-- #create database
-- CREATE USER TICKET_BOOKING IDENTIFIED BY ticketpwd;
-- #grant requried permission 1
-- GRANT CREATE TABLE TO TICKET_BOOKING;
-- #grant requried permission 2
-- GRANT CONNECT, RESOURCE TO TICKET_BOOKING;

-- conn TICKET_BOOKING / ticketpwd;

CREATE TABLE TB_LOCATION (
    LOC_SEQ_ID NUMBER(10),
    LOCATION_NAME VARCHAR2(100),
    CREATED_BY VARCHAR2(100),
    CREATED_ON DATE,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON DATE
);

    INSERT INTO TB_LOCATION (LOC_SEQ_ID, LOCATION_NAME, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
    VALUES (1, 'Nellore', 'admin', SYSDATE, 'admin', SYSDATE);

INSERT INTO TB_LOCATION (LOC_SEQ_ID, LOCATION_NAME, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (2, 'Gudur', 'admin', SYSDATE, 'admin', SYSDATE);

CREATE TABLE ROLES_DTLS (
    ROLE_ID NUMBER PRIMARY KEY,
    ROLE_NAME VARCHAR2(50) NOT NULL UNIQUE
);

insert into ROLES_DTLS (ROLE_ID,ROLE_NAME) values (1,'admin');
insert into ROLES_DTLS (ROLE_ID,ROLE_NAME) values (2,'user');


CREATE TABLE USERS_DTLS (
    SEQ_ID NUMBER PRIMARY KEY,
    PHONE VARCHAR2(50) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    ADDRESS VARCHAR2(100),
    EMAIL VARCHAR2(100),
    PASSWORD VARCHAR2(60) NOT NULL,
    ROLE_ID NUMBER(10),
    CREATED_BY VARCHAR2(100),
    CREATED_ON DATE,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON DATE
);

INSERT INTO USERS_DTLS (SEQ_ID, PHONE, FIRST_NAME, LAST_NAME, ADDRESS, EMAIL, PASSWORD, ROLE_ID, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (1, '9876543210', 'Kushal', 'Kumar', '123 Main St', 'kushal.doe@example.com', 'password123', 1, 'admin', SYSDATE, 'admin', SYSDATE);

INSERT INTO USERS_DTLS (SEQ_ID, PHONE, FIRST_NAME, LAST_NAME, ADDRESS, EMAIL, PASSWORD, ROLE_ID, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (2, '9876543211', 'Sai', 'Ram', '456 Oak Ave', 'jane.smith@example.com', 'password456', 2, 'admin', SYSDATE, 'admin', SYSDATE);


SELECT FIRST_NAME , LAST_NAME as displayName  FROM USERS_DTLS WHERE PHONE='9876543210' AND PASSWORD='password123';

CREATE TABLE TB_SHOWS (
    SHOW_ID NUMBER(10),
    MOVIE_NAME VARCHAR2(100),
    MOVIE_DURATION NUMBER(3),
    THEATRE_NAME VARCHAR2(100),
    LOCATION_NAME VARCHAR2(100),
    CREATED_BY VARCHAR2(100),
    CREATED_ON DATE,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON DATE,
    CONSTRAINT tb_shows_pk PRIMARY KEY (SHOW_ID)
);
CREATE TABLE THEATRE (
    THEATRE_ID NUMBER(10),
    THEATRE_NAME VARCHAR2(100),
    LOCATION_NAME VARCHAR2(100),
    CREATED_BY VARCHAR2(100),
    CREATED_ON DATE,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON DATE
);

drop table TB_SHOWS;

CREATE TABLE SHOW_DTLS(
    SEQ_ID NUMBER(10),
    SHOW_ID NUMBER(10),
    LOC_ID NUMBER(10)
);

CREATE SEQUENCE show_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE booking_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE BOOKINGS (
    BOOKING_ID NUMBER(10) PRIMARY KEY,
    SHOW_NAME VARCHAR2(100),
	THEATRE_NAME VARCHAR2(100),
    LOCATION_NAME VARCHAR2(100),
    STATUS VARCHAR2(100),
    BOOKED_DATE DATE,
    TICKET_RATE NUMBER(10),
    SEAT_NO VARCHAR2(4000),
    CREATED_BY VARCHAR2(100),
    CREATED_ON DATE,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON DATE
);

-- drop table bookings;

CREATE TABLE billing_templates (
    id NUMBER PRIMARY KEY, 
    name VARCHAR2(255) UNIQUE NOT NULL, 
    template_json CLOB NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
